version: "3.7"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./click/init:/docker-entrypoint-initdb.d
      - ./click/config.xml:/etc/clickhouse-server/config.xml
      - ./click/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    restart: on-failure

  app:
    container_name: app
    image: app-image
    environment:
      CLICK_HOST: "clickhouse:8123"
      CLICK_DB: "curdb"
      CLICK_USER: "default"
      CLICK_PASSWORD: ""
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    depends_on:
      - clickhouse
    restart: on-failure